module.exports = {
	GET_TEQUILA : 'GET_TEQUILA',
	ADD_TEQUILA: 'ADD_TEQUILA',
	GET_HISTORIAL: 'GET_HISTORIAL',
	GET_TEQUILA_RESPONSE: 'GET_TEQUILA_RESPONSE',
	GET_HISTORIAL_RESPONSE: 'GET_HISTORIAL_RESPONSE',
	GET_TEQUILERA: 'GET_TEQUILERA',
	GET_TEQUILERA_RESPONSE: 'GET_TEQUILERA_RESPONSE'
}