module.exports = {
	GET_TEQUILA: 'VIEW_ACTION',
	RECEIVE_TEQUILA: 'SERVER_ACTION',
	ADD_HISTORIAL: 'ADD_HISTORIAL',
	RECEIVE_HISTORIAL: 'RECEIVE_HISTORIAL',
	GET_TEQUILERAS: 'GET_TEQUILERAS',
	RECEIVE_TEQUILERAS: 'RECEIVE_TEQUILERAS',
	GET_TEQUILERA: 'GET_TEQUILERA',
	RECEIVE_TEQUILERA: 'RECEIVE_TEQUILERA',
	GET_HISTORIAL : 'GET_HISTORIAL',
	GET_HISTORIAL_RESPONSE: 'GET_HISTORIAL_RESPONSE'
}
