module.exports = {
	GET_TEQUILA: 'VIEW_ACTION',
	RECEIVE_TEQUILA: 'SERVER_ACTION',
	ADD_HISTORIAL: 'ADD_HISTORIAL',
	RECEIVE_HISTORIAL: 'RECEIVE_HISTORIAL',
	GET_TEQUILERAS: 'GET_TEQUILERAS',
	RECEIVE_TEQUILERAS: 'RECEIVE_TEQUILERAS'
}
